#!/usr/bin/env bash
#
# Hardware configuration — the two generated files that hold everything about
# this specific machine.
#
#   hypr/conf/hardware.lua   GPU environment variables for the session
#   waybar/hardware.jsonc    the CPU temperature sensor and the backlight device
#
# Both are gitignored, for the same reason the color files are: they are derived
# from the machine, not written by hand, and versioning them would mean a
# conflict every time the repository lands on a different computer.
#
# This is the step that makes one repository work on the laptop with an RTX and
# on a desktop with an AMD card and no battery.

step_hardware() {
  section "Hardware configuration"
  hardware_write_hypr
  hardware_write_waybar
  return 0
}

# ── hypr/conf/hardware.lua ─────────────────────────────────────────────────
#
# Hyprland reads it through `pcall(require, "conf.hardware")` in hyprland.lua,
# so a clone that has never run the installer simply has no GPU variables set
# instead of failing to start.
#
# What goes in: only the variables that depend on which card is in the machine.
# Everything portable (Qt, GTK, cursor size) stays in conf/env.lua, versioned.
hardware_write_hypr() {
  local target="$DOT_ROOT/hypr/conf/hardware.lua"
  local primary="${GPU_OVERRIDE}"
  [[ "$primary" == "auto" ]] && primary="$DOT_GPU_PRIMARY"

  local body=""
  local has_battery="false"
  [[ -n "$DOT_BATTERY" ]] && has_battery="true"

  case "$primary" in
    nvidia)
      body+='-- ── NVIDIA ───────────────────────────────────────────────────────
--
-- The set recommended by the Hyprland wiki for the proprietary and open
-- kernel modules. LIBVA_DRIVER_NAME is what makes hardware video decoding
-- work in the browser; the GLX variable stops apps from picking Mesa on a
-- machine where both are installed.
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("NVD_BACKEND", "direct")
'
      ;;
    intel)
      body+='-- ── Intel ────────────────────────────────────────────────────────
--
-- iHD is the modern VA-API driver (intel-media-driver, Broadwell and newer).
-- On anything older than 2014 this has to be "i965", from libva-intel-driver.
hl.env("LIBVA_DRIVER_NAME", "iHD")
'
      ;;
    amd)
      body+='-- ── AMD ──────────────────────────────────────────────────────────
--
-- radeonsi is the Mesa VA-API driver. RADV is already the default Vulkan
-- implementation on Arch; the variable is here to make it explicit rather
-- than to change anything.
hl.env("LIBVA_DRIVER_NAME", "radeonsi")
hl.env("AMD_VULKAN_ICD", "RADV")
'
      ;;
    *)
      body+='-- ── Software rendering ───────────────────────────────────────────
--
-- No supported GPU was detected, so this session runs on llvmpipe. Hyprland
-- refuses to start on a software renderer unless it is told to allow it, and
-- hardware cursors do not exist here.
hl.env("WLR_RENDERER_ALLOW_SOFTWARE", "1")
hl.env("LIBGL_ALWAYS_SOFTWARE", "1")

hl.config({
  cursor = {
    no_hardware_cursors = true,
  },
})
'
      ;;
  esac

  # Hybrid laptop: two cards, and Hyprland has to be told which one to render
  # on. The default (the boot GPU, normally the integrated one) is right for
  # battery life, so the override is written as a comment rather than applied.
  if gpu_is_hybrid; then
    local cards=""
    local c
    for c in /dev/dri/card*; do
      [[ -e "$c" ]] && cards+="${cards:+:}$c"
    done
    body+="
-- ── Hybrid graphics ──────────────────────────────────────────────
--
-- This machine has more than one GPU (${DOT_GPUS}). Hyprland renders on the
-- one the firmware booted with, which is the power-saving choice.
--
-- To render the whole session on the discrete card instead, uncomment the
-- line below and put its node first. Check which is which with:
--     for d in /sys/class/drm/card*/device/driver; do echo \"\$d -> \$(readlink -f \$d)\"; done
--
-- hl.env(\"AQ_DRM_DEVICES\", \"${cards}\")
--
-- A single program can also be sent to the discrete card without changing
-- the session, with \`prime-run <program>\` (package nvidia-prime).
"
  fi

  {
    cat <<LUA_EOF
-- GENERATED by ~/.config/install.sh — do not edit.
--
-- Rerun \`~/.config/install.sh --only=hardware\` after changing graphics
-- hardware and this file is rewritten. It is gitignored: it describes this
-- machine, not the configuration.
--
--   host          $(uname -n)
--   generated     $(date '+%Y-%m-%d %H:%M')
--   gpu           ${DOT_GPU_LABEL}
--   drivers       ${DOT_GPUS} (primary: ${primary})
--   form factor   ${DOT_FORM_FACTOR}
--
-- Everything that is true on any machine — Qt, GTK, cursor size, the newt
-- palette — lives in conf/env.lua, which is versioned. Only what depends on
-- the hardware belongs here.

LUA_EOF
    printf '%s\n' "$body"
    cat <<'LUA_EOF'
local M = {}

LUA_EOF
    cat <<LUA_EOF
M.gpu = "${primary}"
M.gpus = "${DOT_GPUS}"
M.form_factor = "${DOT_FORM_FACTOR}"
M.battery = ${has_battery}

return M
LUA_EOF
  } | write_file "$target"
}

# ── waybar/hardware.jsonc ──────────────────────────────────────────────────
#
# Waybar merges every file listed in "include" into the main config, and keys
# already present in config.jsonc win. The two values here are therefore *not*
# in config.jsonc at all — this is where they come from.
#
# Why they cannot be hardcoded:
#
#   temperature  the sensor is coretemp on Intel and k10temp on AMD, and its
#                hwmonN number changes between reboots (driver load order), so
#                the stable device path is used instead.
#   backlight    the device is intel_backlight, amdgpu_bl0 or nvidia_0
#                depending on which driver owns the panel, and a desktop has
#                none at all.
hardware_write_waybar() {
  local target="$DOT_ROOT/waybar/hardware.jsonc"
  local temp_block="" backlight_block=""

  if [[ -n "$DOT_HWMON_PATH" ]]; then
    temp_block="  // Sensor: ${DOT_HWMON_NAME}. hwmon-path-abs points at the device directory,
  // not at /sys/class/hwmon/hwmonN — that number is assigned in driver load
  // order and changes between reboots.
  \"temperature\": {
    \"hwmon-path-abs\": \"${DOT_HWMON_PATH}\",
    \"input-filename\": \"temp1_input\"
  }"
  else
    temp_block="  // No CPU temperature sensor was found on this machine, so the module is
  // left on its own defaults and simply shows nothing.
  \"temperature\": {}"
  fi

  if [[ -n "$DOT_BACKLIGHT" ]]; then
    backlight_block="  // Panel: ${DOT_BACKLIGHT}
  \"backlight\": {
    \"device\": \"${DOT_BACKLIGHT}\"
  }"
  else
    backlight_block="  // No backlight device: a desktop, or a monitor whose brightness is not
  // controlled by the kernel. Waybar finds nothing and hides the module.
  \"backlight\": {}"
  fi

  {
    cat <<JSON_EOF
// GENERATED by ~/.config/install.sh — do not edit.
//
// Pulled into waybar/config.jsonc through its "include" key. Rerun
// \`~/.config/install.sh --only=hardware\` to regenerate.
//
//   host        $(uname -n)
//   generated   $(date '+%Y-%m-%d %H:%M')
{
${temp_block},

${backlight_block}
}
JSON_EOF
  } | write_file "$target"
}
