-- Environment variables. These only apply to processes Hyprland starts after
-- reading the config — already running programs keep the old values, and
-- `hyprctl reload` does not reapply them. Log out and back in to be sure.

-- ── Cursor ───────────────────────────────────────────────────────

-- Both must match: XCURSOR is for X11/XWayland apps, HYPRCURSOR for apps
-- using Hyprland's newer cursor format.
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- ── Toolkits ─────────────────────────────────────────────────────

-- Make Qt apps run on native Wayland and follow the system theme.
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")

-- Tell apps the session is Wayland.
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- GTK backend: Wayland, falling back to X11.
hl.env("GDK_BACKEND", "wayland,x11")

-- Fixes blurry text in Java/Swing apps.
hl.env("_JAVA_AWT_WM_NONREPARENTING", "1")

-- ── TUI ──────────────────────────────────────────────────────────

-- nmtui, whiptail and everything else drawn by newt read their palette from
-- this file, generated by ~/.config/theme/apply.py. Without it newt uses its
-- own built-in colors, which paint the dialogs in "black on lightgray" — two
-- slots that in a themed terminal are almost the same tone, leaving the text
-- unreadable.
--
-- It goes here and not in ~/.zshrc because the bar opens nmtui through
-- `sh -c`, which reads no rc file. Set on the session, every child inherits.
hl.env("NEWT_COLORS_FILE", os.getenv("HOME") .. "/.config/newt/palette")

-- ── Graphics ─────────────────────────────────────────────────────

-- The GPU variables are deliberately NOT here.
--
-- LIBVA_DRIVER_NAME is "nvidia" on one machine, "iHD" on an Intel laptop and
-- "radeonsi" on an AMD desktop, and __GLX_VENDOR_LIBRARY_NAME only makes sense
-- where the NVIDIA driver is installed. This file is identical on every
-- machine, so anything that depends on the hardware would be wrong on half of
-- them.
--
-- They live in conf/hardware.lua, which ~/.config/install.sh writes from what
-- it detects and hyprland.lua loads right after this file. That file is
-- gitignored, like the generated colors.
--
-- After swapping a graphics card, regenerate it with:
--     ~/.config/install.sh --only=hardware

-- Runs Electron apps (VS Code, Discord, Spotify) on native Wayland, which
-- fixes blurry scaling on high-density screens.
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
