-- Appearance: gaps, borders, colors, rounding, shadow and blur.

-- conf/colors.lua is GENERATED by ~/.config/theme/apply.py from
-- ~/.config/theme/palettes.py. Edit palettes.py instead, and switch variants
-- with SUPER+SHIFT+T. Colors arrive as rgba(RRGGBBAA), the format Hyprland wants.
local cores = require("conf.colors")

hl.config({
  general = {
    -- ── Spacing ──────────────────────────────────────────────────
    gaps_in = 5, -- between windows
    gaps_out = 10, -- between windows and the screen edge
    border_size = 2,

    -- ── Border colors ────────────────────────────────────────────
    -- The focused window gets a gradient border; `angle` is the direction
    -- in degrees (45 = diagonal).
    col = {
      active_border = {
        colors = { cores.lavender, cores.mauve },
        angle = 45,
      },
      inactive_border = cores.surface0:gsub("ff%)$", "aa)"),
    },

    -- Allow resizing by dragging the border or the gap between windows.
    resize_on_border = true,

    -- Lets a frame be shown before it finishes drawing: lower latency in
    -- games, at the cost of visible tearing. Enable per window in
    -- windowrules.lua if you turn this on.
    allow_tearing = false,

    layout = "dwindle",
  },

  decoration = {
    -- ── Corners ──────────────────────────────────────────────────
    rounding = 10,
    rounding_power = 2, -- 2 = circular; higher values give a "squircle"

    -- ── Opacity ──────────────────────────────────────────────────
    -- 1.0 is fully opaque. Try inactive_opacity = 0.92 to dim unfocused windows.
    active_opacity = 1.0,
    inactive_opacity = 1.0,

    shadow = {
      enabled = true,
      range = 4, -- reach in pixels
      render_power = 3, -- how quickly the shadow fades out
      color = cores.crust:gsub("ff%)$", "ee)"),
    },

    -- ── Blur behind translucent windows ──────────────────────────
    -- Only visible where something is transparent: the bar, menus, terminals
    -- with background_opacity below 1. `passes` is the expensive setting.
    blur = {
      enabled = true,
      size = 6,
      passes = 2, -- 2 looks good; 3 or more costs a lot of GPU
      vibrancy = 0.1696, -- boosts saturation behind the blur
      noise = 0.012, -- subtle grain, avoids a plastic look
      new_optimizations = true,

      xray = false,
      popups = true, -- blur layers too (bar, rofi menus, swaync)
    },
  },

  animations = {
    enabled = true, -- curves and animations live in conf/animations.lua
  },
})
